/* =============================================================================
   TÊN BỘ THỦ (HÁN VIỆT) — GĐ 12, quyết định 18.42
   =============================================================================

   Chỉ tra tên gọi Hán Việt của 214 bộ thủ Khang Hy (danh sách cố định, không
   phải tự đặt), KHÔNG suy luận nghĩa hay cách ghép chữ. Bảng dưới đây do
   Claude soạn từ kiến thức từ điển Hán Nôm phổ thông, CHƯA CÓ NGƯỜI BIẾT
   TIẾNG TRUNG XÁC MINH LẠI TỪNG CHỮ — xem MucChuaKiemTra ở nơi dùng bảng này.

   Chỉ liệt kê các bộ thủ THỰC SỰ xuất hiện trong dữ liệu chữ Hán của app
   (public/du-lieu/chu-han-hsk*.json, trường "boThu"), không phải đủ 214 bộ.

   HAI CHỖ DỄ NHẦM, cần chủ dự án kiểm tra kỹ:
     - 冖 và 纟/糸 đều đọc Hán Việt là "mịch" nhưng là HAI bộ khác nhau
       (冖 = trùm khăn, 纟/糸 = tơ). Giữ đúng như từ điển, không tự sửa cho
       khỏi trùng.
     - 夂 (truy, "đến/theo sau") và 夊 (tuy, "đi chậm") nhìn gần giống nhau,
       dễ lẫn phông chữ.
   ============================================================================= */

export const TEN_BO_THU = {
  人: "nhân",
  子: "tử",
  女: "nữ",
  车: "xa",
  乙: "ất",
  见: "kiến",
  一: "nhất",
  爪: "trảo",
  讠: "ngôn",
  八: "bát",
  父: "phụ",
  口: "khẩu",
  白: "bạch",
  玉: "ngọc",
  十: "thập",
  勹: "bao",
  木: "mộc",
  辵: "sước",
  疒: "nạch",
  艸: "thảo",
  巾: "cân",
  走: "tẩu",
  凵: "khảm",
  穴: "huyệt",
  广: "nghiễm",
  手: "thủ",
  大: "đại",
  虫: "trùng",
  刀: "đao",
  彳: "xích",
  弓: "cung",
  竹: "trúc",
  火: "hoả",
  田: "điền",
  邑: "ấp",
  寸: "thốn",
  夕: "tịch",
  儿: "nhân (儿)",
  二: "nhị",
  饣: "thực",
  戶: "hộ",
  户: "hộ",
  飞: "phi",
  非: "phi (非)",
  月: "nguyệt",
  高: "cao",
  欠: "khiếm",
  丨: "cổn",
  纟: "mịch (tơ)",
  工: "công",
  犬: "khuyển",
  贝: "bối",
  囗: "vi",
  水: "thuỷ",
  鸟: "điểu",
  几: "kỷ",
  宀: "miên",
  门: "môn",
  廾: "củng",
  目: "mục",
  土: "thổ",
  老: "lão",
  亅: "quyết",
  冫: "băng",
  里: "lý",
  亠: "đầu",
  雨: "vũ",
  心: "tâm",
  丿: "phiệt",
  米: "mễ",
  面: "diện",
  日: "nhật",
  肉: "nhục",
  干: "can",
  牛: "ngưu",
  气: "khí",
  钅: "kim",
  厶: "khư",
  小: "tiểu",
  生: "sinh",
  士: "sĩ",
  示: "thị",
  山: "sơn",
  页: "hiệt",
  文: "văn",
  戈: "qua",
  襾: "á",
  糸: "mịch (tơ nhỏ)",
  冖: "mịch (trùm khăn)",
  斤: "cân (rìu)",
  衣: "y",
  匸: "hễ",
  彡: "sam",
  又: "hựu",
  阜: "phụ (gò đất)",
  冂: "quynh",
  止: "chỉ",
  矢: "thỉ",
  禾: "hoà",
  夂: "truy",
  比: "tỷ",
  力: "lực",
  足: "túc",
  黑: "hắc",
  己: "kỷ (bản thân)",
  攴: "phốc",
  酉: "dậu",
  尢: "uông",
  禸: "nhựu",
  方: "phương",
  毋: "vô",
  色: "sắc",
  身: "thân",
  舌: "thiệt",
  网: "võng",
  丶: "chủ",
  舛: "suyễn",
  鱼: "ngư",
  立: "lập",
  长: "trường",
  自: "tự",
  舟: "chu",
  匕: "chuỷ",
  尸: "thi",
  耳: "nhĩ",
  彐: "kệ",
  殳: "thù",
  而: "nhi",
  风: "phong",
  夊: "tuy",
  曰: "viết",
  瓜: "qua (dưa)",
  黃: "hoàng",
  角: "giác",
  行: "hành",
  靑: "thanh",
  卜: "bốc",
  石: "thạch",
  厂: "hán (mái đá)",
  斗: "đẩu",
  马: "mã",
  毛: "mao",
  隹: "chuy",
  皿: "mãnh",
  片: "phiến",
  瓦: "ngoã",
  入: "nhập",
  甘: "cam",
  卩: "tiết",
  香: "hương",
  革: "cách",
  牙: "nha",
  言: "ngôn (言)",
  羊: "dương",
  音: "âm",
  用: "dụng",
  羽: "vũ (lông)",
};

/** Tên Hán Việt của một bộ thủ, không có trong bảng thì trả về null. */
export function tenBoThu(chuBoThu) {
  return TEN_BO_THU[chuBoThu] ?? null;
}
